# Generated by Django 4.0.4 on 2022-06-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
