# Generated by Django 4.0.4 on 2022-06-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucode', '0002_category_updatedat_product_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
