# Generated by Django 4.0.4 on 2022-06-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucode', '0003_alter_category_updatedat_alter_product_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
