# Generated by Django 4.0.4 on 2022-06-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucode', '0004_alter_product_name_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
