# Generated by Django 4.0.4 on 2022-06-19 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucode', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='placement_Id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
