# Generated by Django 4.0.4 on 2022-06-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menucode', '0006_category_placement_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='placement_Id',
            new_name='placementId',
        ),
    ]
