# Generated by Django 4.0.4 on 2022-06-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucode', '0013_alter_category_placementid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['placementId']},
        ),
        migrations.AlterField(
            model_name='category',
            name='placementId',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
